/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2018-11-26 08:02:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.userManager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class viewUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'viewUser.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<link href=\"images/skin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tmargin-left: 0px;\r\n");
      out.write("\t\tmargin-top: 0px;\r\n");
      out.write("\t\tmargin-right: 0px;\r\n");
      out.write("\t\tmargin-bottom: 0px;\r\n");
      out.write("\t\tbackground-color: #EEF2FB;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write(".STYLE1 {font-size: 12px}\r\n");
      out.write(".STYLE4 {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #1F4A65;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:link {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #06482a;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("a:visited {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #06482a;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:hover {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #FF0000;\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("a:active {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #FF0000;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".STYLE7 {font-size: 12}\r\n");
      out.write("\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t\tvar  highlightcolor='#EEF2FB';\r\n");
      out.write("\t\t//此处clickcolor只能用win系统颜色代码才能成功,如果用#xxxxxx的代码就不行,还没搞清楚为什么:(\r\n");
      out.write("\t\tvar  clickcolor='red';\r\n");
      out.write("\t\tfunction  changeto(){\r\n");
      out.write("\t\tsource=event.srcElement;\r\n");
      out.write("\t\tif  (source.tagName==\"TR\"||source.tagName==\"TABLE\")\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\twhile(source.tagName!=\"TD\")\r\n");
      out.write("\t\tsource=source.parentElement;\r\n");
      out.write("\t\tsource=source.parentElement;\r\n");
      out.write("\t\tcs  =  source.children;\r\n");
      out.write("\t\t//alert(cs.length);\r\n");
      out.write("\t\tif  (cs[1].style.backgroundColor!=highlightcolor&&source.id!=\"nc\"&&cs[1].style.backgroundColor!=clickcolor)\r\n");
      out.write("\t\tfor(i=0;i<cs.length;i++){\r\n");
      out.write("\t\t\tcs[i].style.backgroundColor=highlightcolor;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction  changeback(){\r\n");
      out.write("\t\tif  (event.fromElement.contains(event.toElement)||source.contains(event.toElement)||source.id==\"nc\")\r\n");
      out.write("\t\treturn\r\n");
      out.write("\t\tif  (event.toElement!=source&&cs[1].style.backgroundColor!=clickcolor)\r\n");
      out.write("\t\t//source.style.backgroundColor=originalcolor\r\n");
      out.write("\t\tfor(i=0;i<cs.length;i++){\r\n");
      out.write("\t\t\tcs[i].style.backgroundColor=\"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction  clickto(){\r\n");
      out.write("\t\tsource=event.srcElement;\r\n");
      out.write("\t\tif  (source.tagName==\"TR\"||source.tagName==\"TABLE\")\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\twhile(source.tagName!=\"TD\")\r\n");
      out.write("\t\tsource=source.parentElement;\r\n");
      out.write("\t\tsource=source.parentElement;\r\n");
      out.write("\t\tcs  =  source.children;\r\n");
      out.write("\t\t//alert(cs.length);\r\n");
      out.write("\t\tif  (cs[1].style.backgroundColor!=clickcolor&&source.id!=\"nc\")\r\n");
      out.write("\t\tfor(i=0;i<cs.length;i++){\r\n");
      out.write("\t\t\tcs[i].style.backgroundColor=clickcolor;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\tfor(i=0;i<cs.length;i++){\r\n");
      out.write("\t\t\tcs[i].style.backgroundColor=\"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function subForm(pageNum){\r\n");
      out.write("    \t\r\n");
      out.write("\t\t\tdocument.getElementById('pageNum').value = pageNum;\t\r\n");
      out.write("\t\t\tdocument.forms[0].submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction subGo(index){\r\n");
      out.write("\tvar obj = document.getElementById('goPage').value;\r\n");
      out.write("\tif(obj > index){\r\n");
      out.write("\talert(\"超出页数，请重新填写\");\r\n");
      out.write("\treturn ;\r\n");
      out.write("\t}else if(obj <= 0){\r\n");
      out.write("\t\talert(\"输入页数有误请重新输入\");\r\n");
      out.write("\t\treturn ;\r\n");
      out.write("\t}else{\r\n");
      out.write("\tdocument.getElementById('pageIndex').value = obj;\t\r\n");
      out.write("\t\t\tdocument.forms[0].submit();\r\n");
      out.write("\t }\r\n");
      out.write("  }\r\n");
      out.write("  function checkAll(){\r\n");
      out.write("\tvar obj = document.getElementById(\"all\");\r\n");
      out.write("\tvar arr = document.getElementsByName(\"dels\");\r\n");
      out.write("\tfor(var i = 0; i < arr.length; i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tarr[i].checked = obj.checked;\r\n");
      out.write("\t\t\r\n");
      out.write("\t} \r\n");
      out.write("}\r\n");
      out.write("function subGo(index){\r\n");
      out.write("\tvar obj = document.getElementById('goPage').value;\r\n");
      out.write("\tif(obj > index){\r\n");
      out.write("\talert(\"超出页数，请重新填写\");\r\n");
      out.write("\treturn ;\r\n");
      out.write("\t}else if(obj <= 0){\r\n");
      out.write("\t\talert(\"输入页数有误请重新输入\");\r\n");
      out.write("\t\treturn ;\r\n");
      out.write("\t}else{\r\n");
      out.write("\tdocument.getElementById('pageNum').value = obj;\t\r\n");
      out.write("\t\t\tdocument.forms[0].submit();\r\n");
      out.write("\t }\r\n");
      out.write("  }\r\n");
      out.write("  //跳转到修改页面\r\n");
      out.write("  function preUpdateUser(uid){\r\n");
      out.write("\t \r\n");
      out.write("\twindow.location.href=\"upUser?uid=\"+uid;\r\n");
      out.write("  }\r\n");
      out.write("  function deleteUser(uid){\r\n");
      out.write("  \tif(window.confirm(\"您确定要这么做吗？\")){\r\n");
      out.write("  \t\twindow.location.href=\"delUser?uid=\"+uid;\r\n");
      out.write("  \t}\r\n");
      out.write("  }\r\n");
      out.write("   function checkAll(){\r\n");
      out.write("\tvar obj = document.getElementById(\"all\");\r\n");
      out.write("\tvar arr = document.getElementsByName(\"dels\");\r\n");
      out.write("\tfor(var i = 0; i < arr.length; i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tarr[i].checked = obj.checked;\r\n");
      out.write("\t\t\r\n");
      out.write("\t} \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  <form action=\"selUser\" method=\"post\">\r\n");
      out.write("   \r\n");
      out.write("   <input type=\"hidden\" name=\"method\" value=\"findUser\" id=\"method\"/>\r\n");
      out.write("  <input type=\"hidden\" name=\"uid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.uid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"uid\">\r\n");
      out.write("  <input type=\"hidden\" name=\"idcard\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.idcard }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" name=\"uname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.uname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" name=\"sex\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.sex }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" name=\"address\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("   <input type=\"hidden\" name=\"position\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.position }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" name=\"userLevel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.rid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" name=\"pwd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.pwd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" name=\"phone\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" name=\"pageNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"pageNum\">\r\n");
      out.write("  \r\n");
      out.write("  </form>\r\n");
      out.write("      <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"17\" valign=\"top\" background=\"images/mail_leftbg.gif\"><img src=\"images/left-top-right.gif\" width=\"17\" height=\"29\" /></td>\r\n");
      out.write("    <td valign=\"top\" background=\"images/content-bg.gif\"><table width=\"100%\" height=\"31\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"left_topbg\" id=\"table2\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"31\"><div class=\"titlebt\">显示用户</div></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("     <td width=\"16\" valign=\"top\" background=\"images/mail_rightbg.gif\"><img src=\"images/nav-right-bg.gif\" width=\"16\" height=\"29\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td valign=\"middle\" background=\"images/mail_leftbg.gif\">&nbsp;</td>\r\n");
      out.write("    <td valign=\"top\" bgcolor=\"#F7F8F9\"><table width=\"98%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td colspan=\"2\" valign=\"top\">&nbsp;</td>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("        <td valign=\"top\">&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td colspan=\"2\" valign=\"top\"><span class=\"left_bt\">\r\n");
      out.write("     <!-- startTable -->\t\r\n");
      out.write("     <table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"30\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"15\" height=\"30\"><img src=\"images/tab_03.gif\" width=\"15\" height=\"30\" /></td>\r\n");
      out.write("        <td width=\"1101\" background=\"images/tab_05.gif\"><img src=\"images/311.gif\" width=\"16\" height=\"16\" /> <span class=\"STYLE4\">查询用户显示列表</span></td>\r\n");
      out.write("        <td width=\"281\" background=\"images/tab_05.gif\"><table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"60\"><table width=\"87%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\">\r\n");
      out.write("                        <input type=\"checkbox\" name=\"checkbox62\" value=\"checkbox\" id=\"all\" onClick=\"checkAll()\"/>\r\n");
      out.write("                    </div></td>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\">全选</div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("              </table></td>\r\n");
      out.write("              <td width=\"60\"><table width=\"90%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"><img src=\"images/001.gif\" width=\"14\" height=\"14\" /></div></td>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\">新增</div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("              </table></td>\r\n");
      out.write("              <td width=\"60\"><table width=\"90%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"><img src=\"images/114.gif\" width=\"14\" height=\"14\" /></div></td>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\">修改</div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("              </table></td>\r\n");
      out.write("              <td width=\"52\"><table width=\"88%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"><img src=\"images/083.gif\" width=\"14\" height=\"14\" /></div></td>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\">删除</div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("              </table></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("        <td width=\"14\"><img src=\"images/tab_07.gif\" width=\"14\" height=\"30\" /></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"9\" background=\"images/tab_12.gif\">&nbsp;</td>\r\n");
      out.write("        <td bgcolor=\"#f3ffe3\"><table width=\"99%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#c0de98\" onmouseover=\"changeto()\"  onmouseout=\"changeback()\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"4%\" height=\"26\" background=\"images/tab_14.gif\" class=\"STYLE1\"><div align=\"center\" class=\"STYLE2 STYLE1\">选择</div></td>\r\n");
      out.write("            <td width=\"8%\" height=\"18\" background=\"images/tab_14.gif\" class=\"STYLE1\"><div align=\"center\" class=\"STYLE2 STYLE1\">序号</div></td>\r\n");
      out.write("            <td width=\"10%\" height=\"18\" background=\"images/tab_14.gif\" class=\"STYLE1\"><div align=\"center\" class=\"STYLE2 STYLE1\">登录名</div></td>\r\n");
      out.write("            <td width=\"18%\" height=\"18\" background=\"images/tab_14.gif\" class=\"STYLE1\"><div align=\"center\" class=\"STYLE2 STYLE1\">身份证</div></td>\r\n");
      out.write("            <td width=\"10%\" height=\"18\" background=\"images/tab_14.gif\" class=\"STYLE1\"><div align=\"center\" class=\"STYLE2 STYLE1\">姓名</div></td>\r\n");
      out.write("            <td width=\"6%\" height=\"18\" background=\"images/tab_14.gif\" class=\"STYLE1\"><div align=\"center\" class=\"STYLE2\">性别</div></td>\r\n");
      out.write("             <td width=\"12%\" height=\"18\" background=\"images/tab_14.gif\" class=\"STYLE1\"><div align=\"center\" class=\"STYLE2\">职位</div></td>\r\n");
      out.write("              <td width=\"8%\" height=\"18\" background=\"images/tab_14.gif\" class=\"STYLE1\"><div align=\"center\" class=\"STYLE2\">用户类型</div></td>\r\n");
      out.write("            <td width=\"7%\" height=\"18\" background=\"images/tab_14.gif\" class=\"STYLE1\"><div align=\"center\" class=\"STYLE2\">编辑</div></td>\r\n");
      out.write("            <td width=\"7%\" height=\"18\" background=\"images/tab_14.gif\" class=\"STYLE1\"><div align=\"center\" class=\"STYLE2\">删除</div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("           ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </table></td>\r\n");
      out.write("        <td width=\"9\" background=\"images/tab_16.gif\">&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"29\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"15\" height=\"29\"><img src=\"images/tab_20.gif\" width=\"15\" height=\"29\" /></td>\r\n");
      out.write("        <td background=\"images/tab_21.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"25%\" height=\"29\" nowrap=\"nowrap\"><span class=\"STYLE1\">共");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("条纪录，当前第");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.pageNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.pages }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("页，每页");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.pageSize }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("条纪录</span></td>\r\n");
      out.write("            <td width=\"75%\" valign=\"top\" class=\"STYLE1\"><div align=\"right\">\r\n");
      out.write("              <table width=\"352\" height=\"20\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                  <td width=\"59\" height=\"22\" valign=\"middle\"><div align=\"right\" class=\"STYLE2 STYLE1\">转到第</div></td>\r\n");
      out.write("                  <td width=\"25\" height=\"22\" valign=\"middle\"><span class=\"STYLE7\">\r\n");
      out.write("                    <input name=\"textfield\" type=\"text\" class=\"STYLE1\" style=\"height:20px; width:25px;\" size=\"5\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.pageNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"goPage\"/>\r\n");
      out.write("                  </span></td>\r\n");
      out.write("                  <td width=\"23\" height=\"22\" valign=\"middle\" class=\"STYLE2 STYLE1\">页</td>\r\n");
      out.write("                  <td width=\"30\" height=\"22\" valign=\"middle\"><a onclick=\"subGo('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.pages}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\" style=\"cursor: hand;\"><img src=\"images/go.gif\" width=\"37\" height=\"15\" /></a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("        <td width=\"14\"><img src=\"images/tab_22.gif\" width=\"14\" height=\"29\" /></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("     <!-- endTable -->\r\n");
      out.write("  \r\n");
      out.write("     \t\r\n");
      out.write("</span>\r\n");
      out.write("\t</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("     \r\n");
      out.write("      <tr>\r\n");
      out.write("        \r\n");
      out.write("        <td valign=\"top\"><table width=\"100%\" height=\"144\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"line_table\">\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("    <td background=\"images/mail_rightbg.gif\">&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td valign=\"bottom\" background=\"images/mail_leftbg.gif\"><img src=\"images/buttom_left2.gif\" width=\"17\" height=\"17\" /></td>\r\n");
      out.write("    <td background=\"images/buttom_bgs.gif\"><img src=\"images/buttom_bgs.gif\" width=\"17\" height=\"17\"></td>\r\n");
      out.write("    <td valign=\"bottom\" background=\"images/mail_rightbg.gif\"><img src=\"images/buttom_right2.gif\" width=\"16\" height=\"17\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/userManager/viewUser.jsp(279,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("user");
      // /WEB-INF/userManager/viewUser.jsp(279,11) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.lu}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /WEB-INF/userManager/viewUser.jsp(279,11) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("st");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("           <tr>\r\n");
            out.write("            <td height=\"18\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE1\">\r\n");
            out.write("              <input name=\"dels\" type=\"checkbox\" class=\"STYLE2\" value=\"checkbox\" />\r\n");
            out.write("            </div></td>\r\n");
            out.write("            \r\n");
            out.write("            <td height=\"18\" bgcolor=\"#FFFFFF\" class=\"STYLE2\"><div align=\"center\" class=\"STYLE2 STYLE1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</div></td>\r\n");
            out.write("            <td height=\"18\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE2 STYLE1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.uid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</div></td>\r\n");
            out.write("            <td height=\"18\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE2 STYLE1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.idcard }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</div></td>\r\n");
            out.write("            <td height=\"18\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE2 STYLE1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.uname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</div></td>\r\n");
            out.write("             <td height=\"18\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE2 STYLE1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.sex }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</div></td>\r\n");
            out.write("            <td height=\"18\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE2 STYLE1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.position }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</div></td>\r\n");
            out.write("            <td height=\"18\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE2 STYLE1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.rid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</div></td>\r\n");
            out.write("            <td height=\"18\" bgcolor=\"#FFFFFF\"><div align=\"center\"><img src=\"images/037.gif\" width=\"9\" height=\"9\" /><span class=\"STYLE1\"> [</span><a onclick=\"preUpdateUser('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.uid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("')\" style=\"font-size: 10px; cursor: hand; color: blue; \">编辑</a><span class=\"STYLE1\">]</span></div></td>\r\n");
            out.write("            <td height=\"18\" bgcolor=\"#FFFFFF\"><div align=\"center\"><span class=\"STYLE2\"><img src=\"images/010.gif\" width=\"9\" height=\"9\" /> </span><span class=\"STYLE1\">[</span><a onclick=\"deleteUser('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.uid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("')\" style=\"font-size: 10px; cursor: hand; color: blue; \">删除</a><span class=\"STYLE1\">]</span></div></td>\r\n");
            out.write("          </tr>\t\r\n");
            out.write("           ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/userManager/viewUser.jsp(311,18) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.pageNum  > 1}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  <td width=\"62\" height=\"22\" valign=\"middle\"><div align=\"right\"><a onclick=\"subForm('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\" style=\"cursor: hand;\"><img src=\"images/first.gif\" width=\"37\" height=\"15\"/></a></div></td>\r\n");
          out.write("                  <td width=\"50\" height=\"22\" valign=\"middle\"><div align=\"right\"><a onclick=\"subForm('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.pageNum -1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\" style=\"cursor: hand;\"><img src=\"images/back2.gif\" width=\"43\" height=\"15\" /></a></div></td>\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/userManager/viewUser.jsp(315,18) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.pageNum  < requestScope.userPage.pages }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  <td width=\"54\" height=\"22\" valign=\"middle\"><div align=\"right\"><a onclick=\"subForm('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.pageNum +1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\" style=\"cursor: hand;\"><img src=\"images/next.gif\" width=\"43\" height=\"15\" /></a></div></td>\r\n");
          out.write("                  <td width=\"49\" height=\"22\" valign=\"middle\"><div align=\"right\"><a onclick=\"subForm('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.userPage.pages}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\" style=\"cursor: hand;\"><img src=\"images/last.gif\" width=\"37\" height=\"15\" /></a></div></td>\r\n");
          out.write("                 \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
