/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2018-11-26 07:54:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.operatorManager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class preCreateRenting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'preCreateRenting.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<link href=\"images/skin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("\t <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("My97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("\t <link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("css/public.css\">\r\n");
      out.write("\t <script type=\"text/javascript\">\r\n");
      out.write("\t \r\n");
      out.write("\t \t//根据借车时间计算出应付金额\r\n");
      out.write("\t \tfunction remarkMoney(){\r\n");
      out.write("\t \t\t//获取租车起始时间\r\n");
      out.write("\t \t\tvar startDate = $(\"#beginDate\").val();\r\n");
      out.write("\t \t\tvar returnDate = $(\"#shouldReturnDate\").val();\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t \t\t//去除 “-”符号\r\n");
      out.write("\t \t\tstartDate = startDate.replace(/[&\\|\\\\\\*^%$#@\\-]/g,\"\");\r\n");
      out.write("\t \t\treturnDate = returnDate.replace(/[&\\|\\\\\\*^%$#@\\-]/g,\"\");\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t \t\t//判断时间\r\n");
      out.write("\t \t\tif(returnDate - startDate <= 0){\r\n");
      out.write("\t \t\t\talert(\"还车时间比借车时间还早,你想干啥→_→?帮你清除了,下不为例\");\r\n");
      out.write("\t \t\t\t$(\"#shouldReturnDate\").val(\"\");\r\n");
      out.write("\t \t\t\t$(\"#shouldPayPrice\").val(\"\");\r\n");
      out.write("\t \t\t\t$(\"#imprest\").val(\"\");\r\n");
      out.write("\t \t\t\treturn;\r\n");
      out.write("\t \t\t}\r\n");
      out.write("\t \t\tvar shouldPay = (returnDate - startDate) * 100;\r\n");
      out.write("\t \t\tvar zujin = $(\"#deposit\").val();\r\n");
      out.write("\t \t\tvar money = Math.floor(zujin) + shouldPay\r\n");
      out.write("\t \t\t$(\"#shouldPayPrice\").val( money );\r\n");
      out.write("\t \t}\r\n");
      out.write("\t \r\n");
      out.write("\t \t//日期检测\r\n");
      out.write("\t \tfunction dateCheck(dObj){\r\n");
      out.write("\t \t\tvar dateObj = new Date();\r\n");
      out.write("\t \t\tvar dateTemp = dateObj.getFullYear()+'-'+((dateObj.getMonth()+1)<10 ? \"0\" + dateObj.getMonth()+1 : dateObj.getMonth()+1)+'-'+(dateObj.getDate()<10 ? \"0\"+ dateObj.getDate() : dateObj.getDate());\r\n");
      out.write("\t \t\tdObj = dObj.replace(/-/g, \"/\");\r\n");
      out.write("\t \t\tdateTemp = dateTemp.replace(/-/g, \"/\");\r\n");
      out.write("\t \t\tvar dt2=new Date(Date.parse(dObj));  \r\n");
      out.write("\t \t\tvar dt3 = new Date(Date.parse(dateTemp));\r\n");
      out.write("\t \t\tif(dt2 < dt3){\r\n");
      out.write("\t \t\t\treturn true;\r\n");
      out.write("\t \t\t}else{\r\n");
      out.write("\t \t\t\treturn false;\r\n");
      out.write("\t \t\t}\r\n");
      out.write("\t \t}\r\n");
      out.write("\t \t\r\n");
      out.write("\t \t//起租日期与还车日期时间检测\r\n");
      out.write("\t \tfunction beginDateEndDateCheck(beginDate,endDate){\r\n");
      out.write("\t \t\tbeginDate = beginDate.replace(/-/g, \"/\");\r\n");
      out.write("\t \t\tendDate = endDate.replace(/-/g, \"/\");\r\n");
      out.write("\t \t\tvar begin = new Date(Date.parse(beginDate));\r\n");
      out.write("\t \t\tvar end = new Date(Date.parse(endDate));\r\n");
      out.write("\t \t\tif(end >= begin){\r\n");
      out.write("\t \t\t    return true;\r\n");
      out.write("\t \t\t}else{\r\n");
      out.write("\t \t\t\treturn false;\r\n");
      out.write("\t \t\t}\r\n");
      out.write("\t \t}\r\n");
      out.write("\t \t//检测起租日期是否合法\r\n");
      out.write("\t \tfunction beginDateCheck(){\r\n");
      out.write("\t \tvar beginObj =document.getElementById('beginDate');\r\n");
      out.write("\t\t \tif(dateCheck(beginObj.value)){\r\n");
      out.write("\t\t \t\t alert(\"您输入的时间不合法，请重新输入！\");\r\n");
      out.write("\t\t \t\t beginObj.select();\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t \t}\r\n");
      out.write("\t \t//检测还车日期是否合法\r\n");
      out.write("\t    function shouldReturnDateCheck(){\r\n");
      out.write("\t    var shouldReturnDate =document.getElementById('shouldReturnDate');\r\n");
      out.write("\t\t \tif(dateCheck(shouldReturnDate.value)){\r\n");
      out.write("\t\t \t\t alert(\"您输入的时间不合法，请重新输入！\");\r\n");
      out.write("\t\t \t\t shouldReturnDate.select();\r\n");
      out.write("\t\t \t}else{\r\n");
      out.write("\t\t \t payMoneyCounts();\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t    }\r\n");
      out.write("\t    //提交表单\r\n");
      out.write("\t    function subForm(){\r\n");
      out.write("\t\tvar beginObj =document.getElementById('beginDate');\r\n");
      out.write("\t\tvar shouldReturnDate =document.getElementById('shouldReturnDate');\r\n");
      out.write("\t \tif(dateCheck(beginObj.value) || dateCheck(shouldReturnDate.value)){\r\n");
      out.write("\t \t    alert('您选择的日期不合法 请重新选择');\r\n");
      out.write("\t \t}else{\r\n");
      out.write("\t \t\tif(beginDateEndDateCheck(beginObj.value,shouldReturnDate.value)){\r\n");
      out.write("\t\t\t\tvar sp = $(\"#shouldPayPrice\").val();\r\n");
      out.write("\t\t\t\tvar ip = $(\"#imprest\").val();\r\n");
      out.write("\t\t\t\tvar p = $(\"#price\").val();\r\n");
      out.write("\t\t\t\tif(\"\" == sp || \"\" == ip || \"\" == p || sp.length == 0 || ip.length == 0 || p.length == 0){\r\n");
      out.write("\t\t\t\t\talert(\"请将信息填满再上传\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t \t\t\tdocument.forms[0].submit();\r\n");
      out.write("\t \t\t}else{\r\n");
      out.write("\t\t   \talert(\"起租日期不能大于应还日期，请重新选择时间\");\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\t//钱数计算\r\n");
      out.write("\t\tfunction payMoneyCounts(){\r\n");
      out.write("\t\t\tvar beginObj =document.getElementById('beginDate').value;\r\n");
      out.write("\t\t\tvar shouldReturnDate =document.getElementById('shouldReturnDate').value;\r\n");
      out.write("\t\t\tvar rentPay = document.getElementById('shouldPayPrice');\r\n");
      out.write("\t\t\tvar rentPayCount = document.getElementById('rentprice');\r\n");
      out.write("\t\t\t//押金\r\n");
      out.write("\t\t\tvar deposit = document.getElementById('deposit');\r\n");
      out.write("\t\t\t//预付金\r\n");
      out.write("\t\t\tvar imprest = document.getElementById('imprest');\r\n");
      out.write("\t\t\t    var obj =  GetTime(parseDate(beginObj),'h');\r\n");
      out.write("\t\t\t    var obj2 = GetTime(parseDate(shouldReturnDate),'h');\r\n");
      out.write("\t\t\t    var moneyCount =obj2 - obj;\r\n");
      out.write("\t\t \t\tvar money = Math.round((moneyCount/24)) <= 0? parseInt(rentPayCount.value):(Math.round(moneyCount/24))*parseInt(rentPayCount.value);\r\n");
      out.write("\t\t\t\trentPay.value =money;\r\n");
      out.write("\t\t\t\timprest.value = money+parseInt(deposit.value);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//拆分时间\r\n");
      out.write("\t\tfunction parseDate(strdate){\r\n");
      out.write("\t\t\tvar strYear=strdate.substring(0,4);\r\n");
      out.write("\t\t\tvar strMonth=strdate.substring(5,7);\r\n");
      out.write("\t\t\tvar strDay=strdate.substring(8,10);\r\n");
      out.write("\t\t\tvar strHours=strdate.substring(11,13);\r\n");
      out.write("\t\t\tvar strMinutes=strdate.substring(14,17);\r\n");
      out.write("\t\t\treturn new Date(strYear,strMonth,strDay,strHours,strMinutes); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//计算小时数\r\n");
      out.write("\t\tfunction GetTime(dateM,datetype){\r\n");
      out.write("\t\t     var s;                            // 声明变量。\r\n");
      out.write("\t\t     var MinMilli = 1000 * 60;         // 初始化变量。\r\n");
      out.write("\t\t     var HrMilli = MinMilli * 60;\r\n");
      out.write("\t\t     var DyMilli = HrMilli * 24;\r\n");
      out.write("\t\t     s=\"\";\r\n");
      out.write("\t\t     if (datetype==\"d\"){\r\n");
      out.write("\t\t    s +=Math.round(Math.abs(dateM/DyMilli))+\"天\";\r\n");
      out.write("\t\t     }else if (datetype==\"h\"){\r\n");
      out.write("\t\t    s +=Math.round(Math.abs(dateM/HrMilli))+\"小时\"\r\n");
      out.write("\t\t     }else if (datetype==\"m\"){\r\n");
      out.write("\t\t    s +=Math.round(Math.abs(dateM/MinMilli))+\"分\";\r\n");
      out.write("\t\t     } else{\r\n");
      out.write("\t\t    s +=Math.round(Math.abs(dateM/1000))+\"秒\"\r\n");
      out.write("\t\t     }\r\n");
      out.write("\t     return parseFloat(s);                        // 返回结果。\r\n");
      out.write("       }\r\n");
      out.write("       window.onload= function(){\r\n");
      out.write("       var dateObj =new Date();\r\n");
      out.write("       var beginDate = dateObj.getFullYear()+'-'+((dateObj.getMonth()+1)<10 ? \"0\" + dateObj.getMonth()+1 : dateObj.getMonth()+1)+'-'+(dateObj.getDate()<10 ? \"0\"+ dateObj.getDate() : dateObj.getDate());\r\n");
      out.write("       \t\tdocument.getElementById('beginDate').value = beginDate;\r\n");
      out.write("       }\r\n");
      out.write("\t </script>\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\tbody {\r\n");
      out.write("\t\t\tmargin-left: 0px;\r\n");
      out.write("\t\t\tmargin-top: 0px;\r\n");
      out.write("\t\t\tmargin-right: 0px;\r\n");
      out.write("\t\t\tmargin-bottom: 0px;\r\n");
      out.write("\t\t\tbackground-color: #EEF2FB;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("     <form action=\"");
      out.print(request.getContextPath() );
      out.write("/rentCarByIdCard\" method=\"post\">\r\n");
      out.write("     <input type=\"hidden\"  id=\"rentprice\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${car.rentprice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("     <input type=\"hidden\" name=\"method\" value=\"createRentCarTable\"/>\r\n");
      out.write("     <input type=\"hidden\" id=\"deposit\" name=\"deposit\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${car.deposit }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("     <input type=\"hidden\" name=\"returndate\" value=\"\">\r\n");
      out.write("    <h5><font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font></h5>\r\n");
      out.write("   <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"17\" valign=\"top\" background=\"images/mail_leftbg.gif\"><img src=\"images/left-top-right.gif\" width=\"17\" height=\"29\" /></td>\r\n");
      out.write("    <td valign=\"top\" background=\"images/content-bg.gif\"><table width=\"100%\" height=\"31\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"left_topbg\" id=\"table2\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"31\"><div class=\"titlebt\">生成出租单</div></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("     <td width=\"16\" valign=\"top\" background=\"images/mail_rightbg.gif\"><img src=\"images/nav-right-bg.gif\" width=\"16\" height=\"29\"/></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td valign=\"middle\" background=\"images/mail_leftbg.gif\">&nbsp;</td>\r\n");
      out.write("    <td valign=\"top\" bgcolor=\"#F7F8F9\"><table width=\"98%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td colspan=\"2\" valign=\"top\">&nbsp;</td>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("        <td valign=\"top\">&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td colspan=\"2\" valign=\"top\"><span class=\"center_bt\">\r\n");
      out.write("\t<table class=\"maintable\" width=\"100%\" border=\"0\" cellspacing=\"0\" >\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td width=\"14%\"><div align=\"center\" class=\"left_txt\">出租单编号</div></td>\r\n");
      out.write("      <td width=\"23%\"><input style=\"background-color: #e4e4e4\" type=\"text\" name=\"rentid\" id=\"tableId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.tableId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly></td>\r\n");
      out.write("      <td width=\"15%\"><div align=\"center\" class=\"left_txt\">预付金</div></td>\r\n");
      out.write("      <td width=\"48%\"><input type=\"text\" name=\"imprest\" id=\"imprest\">元(当前车辆押金为：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${car.deposit }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(")</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td><div align=\"center\" class=\"left_txt\" class=\"left_txt\">应付金</div></td>\r\n");
      out.write("      <td><input type=\"text\" name=\"payable\" id=\"shouldPayPrice\" readonly=\"readonly\" style=\"background-color: #e4e4e4\">元</td>\r\n");
      out.write("       <td><div align=\"center\" class=\"left_txt\" class=\"left_txt\">实际交付金额</div></td>\r\n");
      out.write("      <td><input type=\"text\" name=\"priced\" id=\"price\">元</td>\r\n");
      out.write("      \r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td><div align=\"center\" class=\"left_txt\">起租日期</div></td>\r\n");
      out.write("      <td><input class=\"Wdate\" type=\"date\" name=\"begindate\" id=\"beginDate\" onchange=\"remarkMoney()\"></td>\r\n");
      out.write("     <td><div align=\"center\" class=\"left_txt\">应归还日期</div></td>\r\n");
      out.write("     <td><input class=\"Wdate\" type=\"date\" name=\"dateable\" id=\"shouldReturnDate\" onchange=\"remarkMoney()\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td><div align=\"center\" class=\"left_txt\">出租单状态</div></td>\r\n");
      out.write("      <td>\r\n");
      out.write("      <select name=\"status\" id=\"rentFlag\">\r\n");
      out.write("      \t<option value=\"出租中\" class=\"left_txt\">已出租</option>\r\n");
      out.write("      \t<option value=\"未出租\" class=\"left_txt\">未出租</option>\r\n");
      out.write("      </select>\r\n");
      out.write("     <td><div align=\"center\" class=\"left_txt\">汽车编号</div></td>\r\n");
      out.write("     <td>\r\n");
      out.write("    \t<input name=\"carid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${car.carid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly=\"readonly\" style=\"background-color: #e4e4e4\">\r\n");
      out.write("    </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td><div align=\"center\" class=\"left_txt\">客户编号</div></td>\r\n");
      out.write("      <td><input type=\"text\" style=\"background-color: #e4e4e4\" name=\"idcard\" id=\"identity\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.idcard }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly></td>\r\n");
      out.write("     <td><div align=\"center\" class=\"left_txt\">服务人员编号</div></td>\r\n");
      out.write("     <td><input type=\"text\" style=\"background-color: #e4e4e4\" name=\"uid\" id=\"userName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.uid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("  </table>\r\n");
      out.write("<table align=\"left\" width=\"100%\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"107\">\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t<img  src=\"");
      out.print(basePath);
      out.write("images/carimg/ok.gif\" onclick=\"subForm()\" style=\"cursor: hand;\">\r\n");
      out.write("\t\t &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t <img  src=\"");
      out.print(basePath);
      out.write("images/carimg/reset.gif\" onclick=\"reset()\" style=\"cursor: hand;\">\r\n");
      out.write("\t\t  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<img  src=\"");
      out.print(basePath);
      out.write("images/carimg/return.gif\" onclick=\"history.back()\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"30\" background=\"");
      out.print(basePath);
      out.write("images/tab/bg.gif\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</span>\r\n");
      out.write("\t</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("     \r\n");
      out.write("      <tr>\r\n");
      out.write("        \r\n");
      out.write("        <td valign=\"top\"><table width=\"100%\" height=\"144\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"line_table\">\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("    <td background=\"images/mail_rightbg.gif\">&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td valign=\"bottom\" background=\"images/mail_leftbg.gif\"><img src=\"images/buttom_left2.gif\" width=\"17\" height=\"17\" /></td>\r\n");
      out.write("    <td background=\"images/buttom_bgs.gif\"><img src=\"images/buttom_bgs.gif\" width=\"17\" height=\"17\"></td>\r\n");
      out.write("    <td valign=\"bottom\" background=\"images/mail_rightbg.gif\"><img src=\"images/buttom_right2.gif\" width=\"16\" height=\"17\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("  </form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
